<a href="https://colab.research.google.com/github/bumcoding/bumcoding/blob/main/TorchStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#torch : 메인 네임스페이스, 텐서 등의 다양한 수학 함수 포함
#torch.autograd : 자동 미분 기능을 제공하는 라이브러리
#torch.nn : 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
#torch.multiprocessing : 병렬처리 기능을 제공하는 라이브러리
#torch.optim : SGD(확률적 경사하강법)를 중심으로 파라미터 최적화 알고리즘 제공
#torch.utils : 데이터 조작 등 유틸리티 기능 제공
#torch.onnx :(Open Neural Network Exchange)서로 다른 프레임워크 간 모델을 공유

import torch

#텐서 버전 확인
torch.__version__

'2.6.0+cu124'

In [2]:
#초기화 되지 않은 텐서 (랜덤한 형태의 초기화 되지 않는 값(메모리만 할당한 쓰레기 값) 생성)

x = torch.empty(4, 2)
print(x)

tensor([[1.5540e-42, 4.4222e-41],
        [0.0000e+00, 0.0000e+00],
        [2.2421e-44, 4.4222e-41],
        [3.1387e-27, 0.0000e+00]])


In [3]:
#무작위로 초기화 된 텐서 (초기화 된 랜덤의 값 생성)

x = torch.rand(4, 2)
print(x)

tensor([[0.5727, 0.5510],
        [0.8304, 0.3365],
        [0.5364, 0.3905],
        [0.2585, 0.3974]])


In [4]:
#데이터 타입(dtype)이 long이고 0으로 채워진 텐서

x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [5]:
#사용자가 입력한 값으로 텐서 초기화

x = torch.tensor([3, 2.3])
torch.set_printoptions(precision=2) #소수점 2자리까지 출력

print(x)

tensor([3.00, 2.30])


In [6]:
#4x2 크기, double 타입, 1로 채워진 텐서

x = torch.ones(4, 2, dtype=torch.double) # 새로운 텐서 생성
print(x)

x = x.new_ones(4, 2, dtype=torch.double) # x의 속성을 상속 받음

print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [7]:
#x와 같은 크기, float 타입인 무작위로 채워진 텐서

x = torch.randn_like(x, dtype=float)

print(x)

tensor([[ 1.73, -0.35],
        [-0.14, -0.33],
        [-0.30,  0.30],
        [-0.21,  0.39]], dtype=torch.float64)


In [8]:
#텐서의 크기 계산

print(x.size())

torch.Size([4, 2])


In [9]:
#데이터 타입 지정

ft = torch.FloatTensor([1, 2, 3])

print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
#데이터 타입 캐스팅 (디폴트 : int64(=long))

print(ft.double())
print(ft.int()) #int32로 명확히 지정
print(ft.long())

#32bit float = float
#64bit float = double
#18bit float = half
#32bit int = int
#64bit int = torch.long
#18bit int = short

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [11]:
# intTensor 사용

it = torch.IntTensor([1, 2, 3])

print(it)

#타입 캐스팅
print(it.float()) #현재 설정된 기본 dtype과 같으면 생략되어 출력
print(it.double())
print(it.short())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int16)


In [12]:
#CUDA Tensors
#.to 메소드를 이용하여 텐서를 어떤 장치로 옮길 수 있음

x = torch.randn(1)

print(x)
print(x.item())
print(x.dtype)

tensor([1.15])
1.1520277261734009
torch.float32


In [13]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#if문 필요없이 원래 cpu, cuda 중에 선언한 형태로 작동

print(device)

y = torch.ones_like(x, device=device)
print(y)

x = x.to(device)
print(x)

z = x+y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([1.15], device='cuda:0')
tensor([2.15], device='cuda:0')
tensor([2.15], dtype=torch.float64)
